/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cyz14_client4over6_MainActivity */

#ifndef _Included_com_cyz14_client4over6_MainActivity
#define _Included_com_cyz14_client4over6_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cyz14_client4over6_MainActivity_MSG_UPDATEUI
#define com_cyz14_client4over6_MainActivity_MSG_UPDATEUI 0L
/*
 * Class:     com_cyz14_client4over6_MainActivity
 * Method:    RequestInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cyz14_client4over6_MainActivity_RequestInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
